### ISSUE TITLE
Change SLURM command to check job status

### ISSUE THREAD

**Issue by sgatto** [AntaresSimulatorTeam/antares-launcher#1]
RemoteEnvironmentWithSlurm uses the slurm command `sacct -j JOBID` to check the job status.  
`sacct` interacts with a database that is not always correctly working.

The command `scontrol show job JOBID` should be used instead.

Problem: scontrol does not work correctly with "very old" jobs, it answer with an error. The handling of this error should be coded correctly.

**Comment by sgatto** [comment]
I think we should use both,
first we try couple of time `sacct` if we receive no asnwer, we call `scontrol`

**Comment by laurent-laporte-pro** [comment]
duplicate: #43
