### ISSUE TITLE
chage unit_tests: remove dependency to `definitions`

### ISSUE THREAD

**Issue by sgatto** [AntaresSimulatorTeam/antares-launcher#7]
tests\unit  (3 usages found)
                test_main_option_parser.py  (1 usage found)
                    5 from antareslauncher import definitions
                test_remote_environment_with_slurm.py  (1 usage found)
                    8 from antareslauncher import definitions
                test_study_list_composer.py  (1 usage found)
                    6 from antareslauncher import definitions

**Comment by laurent-laporte-pro** [comment]
Solved in [v1.2.0](https://github.com/AntaresSimulatorTeam/antares-launcher/releases/tag/v1.2.0)
